### ISSUE TITLE
Bug in setTags

### ISSUE THREAD

**Issue by pbaggiol** [poyhsiao/exiftool-kit#2]
I am running into issues with setTags where on success it isn't returning to the caller.  It looks as though on success, when a source filename string is provided the promise is not satisfied.  When I added  "resolve" calls to the section below, it seems to have fixed it.

```
            if (typeof source === 'string') {
              return unlinkFile(`${source}_original`)
              .then(() => {
                return resolve(source);
              })
              .catch(() => {
                return resolve(source);
              })
```

**Comment by poyhsiao** [comment]
fixed at v0.1.7
